# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: local
    hooks:
    -   id: pre-commit
        name: running pre-commit processes
        language: system
        entry: make pre-commit

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files

exclude: "assets"