services:
  db:
    image: postgres:18-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-easyspell_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-easyspell_pass}
      POSTGRES_DB: ${POSTGRES_DB:-easyspell}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  easyspell:
    build: .
    container_name: easyspell
    volumes:
      - .:/app
      - easyspell_venv:/app/.venv
    working_dir: /app
    command: ["uv", "run", "src/easyspell/cli.py", "dev", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-easyspell_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-easyspell_pass}
      POSTGRES_DB: ${POSTGRES_DB:-easyspell}
    depends_on:
      - db


volumes:
  easyspell_venv:
  pgdata:
